name: IDE Tests

on:
  push:
    branches: [main, "dev-tools/IDE-Tests-workflow"]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  workflow_dispatch:
    inputs:
      iota_repo_ref:
        description: "Branch / commit to test"
        type: string
        required: false
        default: ''

jobs:
  diff:
    runs-on: [self-hosted]
    outputs:
      isMoveAutoFormatter: ${{ steps.diff.outputs.isMoveAutoFormatter }}
      isMoveIDE: ${{ steps.diff.outputs.isMoveIDE }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # Pin v4.1.1
      - name: Detect Changes
        uses: './.github/actions/diffs'
        id: diff

  move-auto-formatter-ci-test:
    name: Move Auto-formatter Test
    needs: diff
    if: needs.diff.outputs.isMoveAutoFormatter == 'true'
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
        with:
          ref: ${{ github.event.inputs.iota_repo_ref || github.ref }}

      - name: pnpm setup
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # pin@v3.0.0
        with:
          version: 9.1.1

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v4.0.2
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ./external-crates/move/crates/move-analyzer/prettier-plugin
        run: npm install && npm i web-tree-sitter

      - name: Run npm test
        working-directory: ./external-crates/move/crates/move-analyzer/prettier-plugin
        shell: bash
        run: npm run test

  move-ide-ci-test:
    name: Move IDE Test
    needs: diff
        # TODO: make this work
    # if: needs.diff.outputs.isMoveIDE == 'true'
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
        with:
          ref: ${{ github.event.inputs.iota_repo_ref || github.ref }}

      - name: pnpm setup
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # pin@v3.0.0
        with:
          version: 9.6.0

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v4.0.2
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ./external-crates/move/crates/move-analyzer/editors/code
        run: |
          sudo apt install libgtk-3-0 -y
          sudo apt-get install -y xvfb x11-apps x11-xkb-utils libx11-6 libx11-xcb1
          set -eux
          # Start server
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 &
          sleep 1
          ps aux | grep Xvfb --color=always | grep -v grep
          pnpm install && pnpm add -D @types/node @types/semver

      - name: Run pnpm test
        working-directory: ./external-crates/move/crates/move-analyzer/editors/code
        shell: bash
        run: DISPLAY=:99.0 pnpm run test

  move-ide-ci-build:
    name: Move IDE build
    needs: diff
    if: needs.diff.outputs.isMoveIDE == 'true'
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
        with:
          ref: ${{ github.event.inputs.iota_repo_ref || github.ref }}

      - name: pnpm setup
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # pin@v3.0.0
        with:
          version: 9.6.0

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v4.0.2
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ./external-crates/move/crates/move-analyzer/editors/code
        run: pnpm install

      - name: Run pnpm test
        working-directory: ./external-crates/move/crates/move-analyzer/editors/code/scripts
        run: ./create.sh -pkg
